// Explanations are separate from parsing so new formats can bring their own vocabulary.
export const boxes = {
  ftyp: ['File type', 'identity', 'The file introduces itself here. Brands describe the container specifications it follows; they are not the video codec.', 'Read the major brand, then the compatible brands. “qt  ” identifies QuickTime.'],
  moov: ['Movie', 'container', 'The map of the movie: its timeline, tracks, and the tables needed to locate encoded samples.', 'Expand a trak to follow one stream from metadata to its media bytes.'],
  mdat: ['Media data', 'media', 'The encoded audio and video samples live here. Their boundaries are described by track tables, not by nested boxes.', 'Open a chunk-offset table (stco or co64) and follow an offset into this payload.'],
  free: ['Free space', 'other', 'Reserved or unused bytes. Writers can use this space to update metadata without relocating the rest of a file.', 'The next box starts at this offset plus this box’s size.'],
  skip: ['Unused space', 'other', 'Padding that readers can skip using the size in the header.', 'Even unused bytes have a place in the file layout.'],
  wide: ['Wide placeholder', 'other', 'A QuickTime placeholder that can reserve space for a larger adjacent atom header.', 'Notice its small size and the atom that follows it.'],
  trak: ['Track', 'container', 'One independently timed stream in the movie, commonly video, audio, or subtitles.', 'tkhd identifies the track; mdia explains its media.'],
  mdia: ['Media', 'container', 'Describes the kind of media in a track and the time units used for its samples.', 'Compare the mdhd timescale with the movie’s mvhd timescale.'],
  minf: ['Media information', 'container', 'Holds media-specific information, data references, and the sample table.', 'Continue into stbl to find the sample index.'],
  stbl: ['Sample table', 'container', 'The index joining time, sample sizes, chunk membership, and file offsets.', 'Use stts → stsc → stsz → stco/co64 to understand how a player finds bytes.'],
  mvhd: ['Movie header', 'timing', 'Defines the movie’s time units and overall duration. Track edit durations use this movie timescale.', 'Divide duration by timescale to convert ticks into seconds.'],
  tkhd: ['Track header', 'timing', 'Identifies a track and records its duration in movie time units, display dimensions, and presentation properties.', 'A track’s display dimensions are not necessarily the encoded pixel dimensions.'],
  mdhd: ['Media header', 'timing', 'Defines the media timescale and duration for this track. Audio and video often use different time units.', 'A duration of 48,000 ticks at 48,000 ticks/second is one second.'],
  hdlr: ['Handler', 'identity', 'Identifies the role of a stream. Common handler types are vide (video), soun (audio), and text or subt (subtitles).', 'This tells you what the track does; stsd describes how samples are encoded.'],
  stsd: ['Sample descriptions', 'identity', 'Lists sample entries containing codec identifiers and format-specific settings.', 'Expand an entry such as avc1 or mp4a. The container and the codec are separate concepts.'],
  stts: ['Decoding time to sample', 'timing', 'A run-length table: each row says how many consecutive samples share a decoding duration.', 'Sample count × sample delta gives the duration of a run in media ticks.'],
  ctts: ['Composition time offsets', 'timing', 'Adds an offset to decoding time to obtain presentation time. Reordered video frames may be decoded before they are displayed.', 'Version 1 offsets can be negative. These offsets use the media timescale.'],
  stsc: ['Sample to chunk', 'index', 'Describes runs of chunks with the same sample count and sample-description index. Chunk numbering starts at 1.', 'A row applies from first_chunk until the next row’s first_chunk.'],
  stsz: ['Sample sizes', 'index', 'Stores a fixed size for all samples, or one size per sample. Sizes let a reader split chunk data into samples.', 'If sample_size is nonzero, there is no per-sample size table.'],
  stz2: ['Compact sample sizes', 'index', 'A compact alternative to stsz using 4-, 8-, or 16-bit size entries.', 'This explorer shows the box bytes; compact entries are not decoded yet.'],
  stco: ['Chunk offsets', 'index', 'Lists absolute 32-bit byte positions for chunks. A chunk groups consecutive samples for this track.', 'Click an offset to jump directly to that byte in the file.'],
  co64: ['64-bit chunk offsets', 'index', 'Like stco, with 64-bit positions for files that need larger offsets.', 'These offsets point to chunk data, not to box headers.'],
  stss: ['Sync samples', 'index', 'Lists sample numbers that are sync points, usually suitable starting points for decoding.', 'These are sample numbers, starting at 1, rather than byte offsets.'],
  edts: ['Edits', 'container', 'Holds edits that map the media timeline into the movie timeline.', 'An edit can trim or delay a track without rewriting its encoded samples.'],
  elst: ['Edit list', 'timing', 'Maps movie-time segments to media-time positions. A media time of −1 represents an empty edit.', 'Segment duration uses the movie timescale; media time uses the track’s media timescale.'],
  dinf: ['Data information', 'container', 'Describes where this track’s media data is stored.', 'Most ordinary MP4 files refer to data inside the same file.'],
  dref: ['Data references', 'index', 'Lists locations of media data. An entry may refer to this file or to an external resource.', 'External resources are never fetched by this explorer.'],
  udta: ['User data', 'container', 'A container for optional metadata supplied by the file’s creator or software.', 'Unknown children are still inspectable as bytes.'],
  meta: ['Metadata', 'container', 'Holds metadata structures. ISO and QuickTime files may use different layouts before its children.', 'The parser checks for the ISO version/flags prefix before walking child boxes.'],
  ilst: ['Metadata items', 'container', 'A collection of tagged metadata items, often used for titles, artists, and software tags.', 'Item payloads may follow vendor-specific conventions.'],
  moof: ['Movie fragment', 'container', 'Metadata for a fragment of a movie, commonly followed by an mdat containing its samples.', 'Fragmented files use traf and trun instead of relying only on the initial sample tables.'],
  traf: ['Track fragment', 'container', 'Metadata for a single track within a movie fragment.', 'Follow tfhd, tfdt, and trun to understand this fragment.'],
  mvex: ['Movie extends', 'container', 'Signals that more movie data will arrive in fragments and provides defaults for them.', 'Look for moof boxes elsewhere in the file.'],
  tfhd: ['Track fragment header', 'index', 'Identifies the track and optional defaults for a fragment.', 'Its flags control which fields are present. Fragment sample addressing is not yet resolved here.'],
  tfdt: ['Track fragment decode time', 'timing', 'Gives the initial decoding time for a track fragment.', 'This is expressed in the track’s media timescale.'],
  trun: ['Track fragment run', 'index', 'Describes samples in a fragment, with fields selected by flags.', 'Raw bytes are available; full fragment sample tracing is a future extension.'],
  mfhd: ['Movie fragment header', 'index', 'Contains the fragment sequence number.', 'Sequence numbers describe fragment order.'],
  uuid: ['User extension', 'other', 'A box with a 16-byte extended type identifier after the usual header.', 'Its payload is specific to that identifier and remains undecoded.'],
  cmov: ['Compressed movie metadata', 'other', 'An older QuickTime layout containing compressed movie metadata.', 'Decompression is not supported. The stored bytes are available for inspection.'],
  avc1: ['H.264 video sample entry', 'identity', 'Describes AVC/H.264 video samples, including encoded dimensions and decoder configuration.', 'The avcC child carries codec setup, not a video frame.'],
  avc3: ['H.264 video sample entry', 'identity', 'An AVC sample entry that permits parameter sets in the samples.', 'Inspect its dimensions and avcC configuration.'],
  hvc1: ['HEVC video sample entry', 'identity', 'Describes HEVC video samples and their decoder configuration.', 'A browser may not support playback even though the structure is readable.'],
  hev1: ['HEVC video sample entry', 'identity', 'An HEVC sample entry with in-band parameter-set capabilities.', 'The hvcC child contains decoder configuration.'],
  mp4a: ['MPEG-4 audio sample entry', 'identity', 'Describes audio samples, commonly AAC, and associated decoder configuration.', 'Its entry fields describe audio format settings; esds can contain more precise codec configuration.'],
  vmhd: ['Video media header', 'identity', 'Holds graphics-mode and color information used for video presentation.', 'The video codec itself is described in stsd, not here.'],
  smhd: ['Sound media header', 'identity', 'Holds basic sound presentation properties, including balance.', 'The audio sample description contains codec and sample-entry information.'],
  nmhd: ['Null media header', 'identity', 'A media header for tracks that do not need a specialized media header.', 'Look at hdlr and stsd to learn what the track contains.'],
  'url ': ['URL data reference', 'index', 'Describes where a sample description gets its media data. The self-contained flag means the data is in this file.', 'A flags value with its lowest bit set selects in-file media. No external reference is fetched.'],
  'urn ': ['Named data reference', 'index', 'A named reference to media data, potentially outside this file.', 'External media locations are not followed by the explorer.'],
  avcC: ['AVC decoder configuration', 'identity', 'Holds configuration used to initialize an H.264 decoder, including parameter sets and the width of NAL-unit lengths.', 'Inspect the bytes here separately from the encoded samples in mdat.'],
  hvcC: ['HEVC decoder configuration', 'identity', 'Contains codec setup used to initialize an HEVC decoder.', 'Configuration data describes how to read samples; it is not a movie frame.'],
  esds: ['Elementary stream descriptor', 'identity', 'Contains nested MPEG-4 descriptors, including information needed to initialize the decoder.', 'Descriptors have their own layout and are not parsed as ordinary MP4 child boxes.'],
  pasp: ['Pixel aspect ratio', 'identity', 'Describes the relative horizontal and vertical spacing of pixels.', 'Pixel shape and the encoded width and height together affect the displayed shape.'],
  btrt: ['Bitrate information', 'identity', 'Contains buffer-size and bitrate information for a sample entry.', 'Bitrate values describe the encoded stream rather than the whole container size.'],
  wave: ['QuickTime audio extension', 'other', 'Contains QuickTime audio-format extension data and nested codec information.', 'This extension remains opaque in the current parser; its bytes are available below.'],
  chan: ['Audio channel layout', 'identity', 'Describes speaker positions or other channel-layout information.', 'Channel layout is more specific than a simple channel count.'],
  sgpd: ['Sample group descriptions', 'index', 'Defines properties shared by groups of samples.', 'The companion sbgp box maps samples to these descriptions.'],
  sbgp: ['Sample to group', 'index', 'Maps runs of samples to group descriptions.', 'Group interpretation depends on the grouping type and sgpd descriptions.'],
  trex: ['Track fragment defaults', 'index', 'Provides default sample properties for fragments belonging to a track.', 'tfhd and trun can override these defaults for individual fragments.'],
};

export function describe(type) {
  const [name, category, explanation, tip] = boxes[type] || ['Unexpanded box', 'other', 'This box is not decoded yet. Its declared boundaries and raw bytes are still available. A four-character type alone does not guarantee a known payload layout.', 'Use the size to locate the next box. Avoid treating arbitrary payload bytes as child boxes.'];
  return { name, category, explanation, tip };
}

export const lessons = [
  ['Start with a box', 'ftyp', 'Read the first eight bytes: four for the total size, four for the type. Multi-byte integers in these headers are big-endian: the most significant byte comes first. Select a decoded field to highlight its exact bytes.'],
  ['Find the movie’s map', 'moov', 'The movie box organizes the information a player needs. It can appear before or after the media data. Metadata near the beginning helps progressive playback start without first reaching the end of the file.'],
  ['Follow one track', 'trak', 'Video and audio are separate tracks. Each has an identifier, a media handler, its own time units, and sample descriptions. Open the Tracks tab to compare them.'],
  ['Turn ticks into seconds', 'mdhd', 'A timescale is the number of ticks per second. Divide a known duration by its timescale. Movie time and media time can differ, and edit lists map between them.'],
  ['Find the encoded bytes', 'stco', 'Sample timing, chunk mapping, sample sizes, and chunk offsets work together. In a chunk-offset table, click a byte position to land inside the media data. Fragmented movies use a different path through moof and traf.'],
  ['Separate container from codec', 'mdat', 'MP4 and MOV organize streams; codecs such as H.264 and AAC encode their content. Reading a container reveals where samples are and how to time them, but decoding a picture or sound requires the corresponding codec.'],
];
